from sqlmodel import SQLModel, Field

# This class represents a database table using ORM
class Weapon(SQLModel, table=True):
    # 'table=True' tells SQLModel that this is a real table in the database

    # Primary key column, auto-generated by the database (AUTO_INCREMENT)
    id: int | None = Field(default=None, primary_key=True)

    # Regular text columns in the database
    name: str         # Weapon name
    type: str         # Weapon type (e.g., firearm, cold)
    price: float      # Weapon price
